[params]
# color style
color = 'gray' # linen, wheat, gray, light

# header social icons
# twitter = 'YOUR_TWITTER_ID'     # twitter.com/YOUR_TWITTER_ID
github = 'mag1c1an1' # github.com/YOUR_GITHUB_ID
# instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
# linkedin = 'YOUR_LINKEDIN_ID'   # linkedin.com/in/YOUR_LINKEDIN_ID
# mastodon = 'YOUR_MASTODON_LINK' # e.g. 'https://mastodon.instance/@xxx'
rss = false # show rss icon

# home page profile
# avatar = 'GRAVATAR_EMAIL' # gravatar email or image url
name = 'MaG1ciaN'
bio = 'Never'


# misc
disableHLJS = true                       # disable highlight.js
disablePostNavigation = true             # disable post navigation
monoDarkIcon = true                      # show monochrome dark mode icon
gravatarCdn = 'GRAVATAR_CDN_LINK'        # e.g. 'https://cdn.v2ex.com/gravatar/'
graphCommentId = "YOUR_GRAPH_COMMENT_ID" # use graph comment (disqus alternative)
math = true                              # enable KaTeX math typesetting globally

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"
